'use strict';

const constants = {
	CHANGE: "CHANGE",
	FETCH_COLUMNS: "FETCH_COLUMNS",
	FETCH_ROWS: "FETCH_ROWS",
	COL_SORT: "COL_SORT",
	MOVE_PAGE: "MOVE_PAGE",
	ROWS_PER_PAGE: "ROWS_PER_PAGE",
	SET_DATA_SOURCE: "SET_DATA_SOURCE"
};

export default constants;
