'use strict';

const constants = {
	CHANGE: "CHANGE",
	FETCH_COLUMNS: "FETCH_COLUMNS",
	FETCH_ROWS: "FETCH_ROWS",
	COL_SORT: "COL_SORT",
	MOVE_PAGE: "MOVE_PAGE",
	ROWS_PER_PAGE: "ROWS_PER_PAGE",
	BOOTSTRAP: "BOOTSTRAP",
	SET_GROUP: "SET_GROUP",
	SEARCHING: "SEARCHING",
	DATE_SELECTED: "DATE_SELECTED",
	SET_DATA_URI: "SET_DATA_URI"
};

export default constants;
