const constants = {
	CHANGE: "CHANGE",
	FETCH_COLUMNS: "FETCH_COLUMNS",
	FETCH_ROWS: "FETCH_ROWS",
	COL_SORT: "COL_SORT",
	MOVE_PAGE: "MOVE_PAGE",
	ROWS_PER_PAGE: "ROWS_PER_PAGE",
	BOOTSTRAP: "BOOTSTRAP",
	SET_GROUP: "SET_GROUP",
	SEARCHING: "SEARCHING",
	DATE_SELECTED: "DATE_SELECTED",
	DATE_RANGE_CHANGE: "DATE_RANGE_CHANGE",
	SET_DATA_URI: "SET_DATA_URI",
	ROW_CLICKED: "ROW_CLICKED",
	SET_ELEMENT: "SET_ELEMENT",
	CELL_CLICKED: "CELL_CLICKED"
};

export default constants;
